# Generated by Django 4.0.1 on 2022-01-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_rename_sales_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='unit_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
