# Generated by Django 4.0.1 on 2022-01-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sale_unit_cost_alter_sale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_priority',
            field=models.CharField(choices=[('H', 'H'), ('C', 'C'), ('L', 'L'), ('M', 'M')], default='H', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_channel',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20),
        ),
    ]
